### ISSUE TITLE
CI LaTeX

### ISSUE THREAD

**Issue by VolkerStolz** [jakobkhansen/master-thesis#1]
I'm tool lazy for a pull-request :-)

```
name: Build
on: [push, workflow_dispatch]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile document.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
```
